### PR TITLE
Add carousel to about page

### PR DESCRIPTION
**Pull request by falconis**
Issue no: #19 
Each image was converted to a size of 1mb each, please check for clarity. :smiley: 
abou21
abou20

### CODE REVIEW

**Comment by falconis** [comment]
Pls review @pradeepgangwar .

**Comment by pradeepgangwar** [comment]
@falconis please share your email so that i can forward you content. Look good.

**Comment by falconis** [comment]
panivishal17@gmail.com

**Comment by pradeepgangwar** [comment]
mailed you. Also please close previous PR and put a live link here after enabling gh-pages on your fork.

**Comment by falconis** [comment]
Updated issue no: #19.
Added about us page content.
[link](https://falconis.github.io/Aparoksha-18/about/)

**Comment by pradeepgangwar** [comment]
Looks good.

**Pull request merged**
