### PR TITLE
Aligned close button on register tab

### LINKED ISSUE #6: Align closing button in fest registration modal
screenshot from 2018-01-10 20-40-23

The Cross button looks a bit off

### PR DESCRIPTION
**Pull request by Re42**
fixes #6

### CODE REVIEW

**Comment by Re42** [comment]
Here are screenshots
image

**Comment by pradeepgangwar** [comment]
@Re42 What about Events Box?

**Comment by Re42** [comment]
We're only using one "button" for both boxes... So, though in events boxes this is aligned vertically, it doesn't align horizontally (it's too close to the border), but changing that would mess with this one.
Should I figure something out for that too?

**Comment by shreyanshdwivedi** [comment]
@Re42 If you can add a new close button for events box, then please go ahead. Else, leave a comment here

**Comment by Re42** [comment]
https://re42.github.io/Aparoksha-18/register/index.html

I used jQuery! live page for review. (Could you raise the difficulty of issue?)

**Comment by pradeepgangwar** [comment]
@Re42 Difficulty level increased. @shreyanshdwivedi @CodHeK  Does it look fine now?

**Comment by pradeepgangwar** [comment]
Looks good to me

**Pull request merged**
